#define  YY_USE_LINENO 1

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

/* First, we deal with  platform-specific or compiler-specific issues. */
 
/* %- */
/* begin standard C headers. */
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
/* end standard C headers. */
/* %+ */
/* %* */

#ifdef __cplusplus

/* C++ compilers don't understand traditional function definitions. */
#ifdef YY_TRADITIONAL_FUNC_DEFS
#undef YY_TRADITIONAL_FUNC_DEFS
#endif
/* %+ */
/* %* */

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* We're not in a C++ compiler, so by default,
   we generate traditional function defs, unless you explicitly ask
   for C99 defs. */

#ifndef YY_NO_TRADITIONAL_FUNC_DEFS
#ifndef YY_TRADITIONAL_FUNC_DEFS
#define YY_TRADITIONAL_FUNC_DEFS
#endif
#endif

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* For compilers that can't handle prototypes.
 * e.g.,
 * The function prototype
 *    int foo(int x, char* y);
 *
 * ...should be written as
 *    int foo YY_PARAMS((int x, char* y));
 *
 * ...which could possibly generate
 *    int foo ();
 */
#ifdef YY_NO_PROTOS
#define YY_PARAMS(proto) ()
#else
#define YY_PARAMS(proto) proto
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

#ifdef YY_REENTRANT

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For use wherever a Global is accessed or assigned. */
#define YY_G(var) (((struct yyguts_t*)yyscanner)->var)

/* For use in function prototypes to append the additional argument. */
#define YY_PROTO_LAST_ARG , yyscan_t yyscanner
#define YY_PROTO_ONLY_ARG    yyscan_t yyscanner

/* For use in function definitions to append the additional argument. */
#ifdef YY_TRADITIONAL_FUNC_DEFS
#define YY_DEF_LAST_ARG , yyscanner
#define YY_DEF_ONLY_ARG    yyscanner
#else
#define YY_DEF_LAST_ARG , yyscan_t yyscanner
#define YY_DEF_ONLY_ARG   yyscan_t yyscanner
#endif
#define YY_DECL_LAST_ARG yyscan_t yyscanner;

/* For use in function calls to pass the additional argument. */
#define YY_CALL_LAST_ARG  , yyscanner
#define YY_CALL_ONLY_ARG   yyscanner

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin YY_G(yyin_r)
#define yyout YY_G(yyout_r)
#define yyextra YY_G(yyextra_r)
#define yyleng YY_G(yyleng_r)
#define yytext YY_G(yytext_r)
#define yylineno YY_G(yylineno_r)
#define yy_flex_debug YY_G(yy_flex_debug_r)

int yylex_init YY_PARAMS((yyscan_t* scanner));

#else /* not YY_REENTRANT */

/* Define these macros to be no-ops. */
#define YY_G(var) (var)
#define YY_PROTO_LAST_ARG
#define YY_PROTO_ONLY_ARG void
#define YY_DEF_LAST_ARG
#ifdef YY_TRADITIONAL_FUNC_DEFS
#define YY_DEF_ONLY_ARG
#else
#define YY_DEF_ONLY_ARG void
#endif
#define YY_DECL_LAST_ARG
#define YY_CALL_LAST_ARG
#define YY_CALL_ONLY_ARG

#endif


/* For compilers that need traditional function definitions.
 * e.g.,
 * The function prototype taking 2 arguments
 *    int foo (int x, char* y)
 *
 * ...should be written as
 *    int foo YYFARGS2(int,x, char*,y)
 *
 * ...which could possibly generate
 *    int foo (x,y,yyscanner)
 *        int x;
 *        char * y;
 *        yyscan_t yyscanner;
 */
#ifdef YY_TRADITIONAL_FUNC_DEFS
/* Generate rtaditional function defs */
#define YYFARGS0(v) (YY_DEF_ONLY_ARG) YY_DECL_LAST_ARG
#define YYFARGS1(t1,n1) (n1 YY_DEF_LAST_ARG) t1 n1; YY_DECL_LAST_ARG
#define YYFARGS2(t1,n1,t2,n2) (n1,n2 YY_DEF_LAST_ARG) t1 n1; t2 n2; YY_DECL_LAST_ARG
#define YYFARGS3(t1,n1,t2,n2,t3,n3) (n1,n2,n3 YY_DEF_LAST_ARG) t1 n1; t2 n2; t3 n3; YY_DECL_LAST_ARG
#else
/* Generate C99 function defs. */
#define YYFARGS0(v) (YY_DEF_ONLY_ARG)
#define YYFARGS1(t1,n1) (t1 n1 YY_DEF_LAST_ARG)
#define YYFARGS2(t1,n1,t2,n2) (t1 n1,t2 n2 YY_DEF_LAST_ARG)
#define YYFARGS3(t1,n1,t2,n2,t3,n3) (t1 n1,t2 n2,t3 n3 YY_DEF_LAST_ARG)
#endif

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN YY_G(yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((YY_G(yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin YY_CALL_LAST_ARG )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif


#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_REENTRANT
extern size_t yyleng;
#endif

/* %- */
#ifndef YY_REENTRANT
extern FILE *yyin, *yyout;
#endif
/* %* */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#ifdef YY_USE_LINENO
/* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
 *       access to the local variable yy_act. Since yyless() is a macro, it would break
 *       existing scanners that call yyless() from OUTSIDE yylex. 
 *       One obvious solution it to make yy_act a global. I tried that, and saw
 *       a 5% performance hit in a non-yylineno scanner, because yy_act is
 *       normally declared as a register variable-- so it's not worth it.
 */
#define  YY_LESS_LINENO(n) \
        do { \
			int yyl;\
			for ( yyl = n; yyl < yyleng; ++yyl )\
				if ( yytext[yyl] == '\n' )\
					--yylineno;\
        }while(0)
#else
#define YY_LESS_LINENO(n)
#endif

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        YY_LESS_LINENO(n);\
		*yy_cp = YY_G(yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		YY_G(yy_c_buf_p) = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, YY_G(yytext_ptr) YY_CALL_LAST_ARG )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %- */
	FILE *yy_input_file;
/* %+ */
/* %* */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %- Standard (non-C++) definition */
/* %c */
#ifndef yyIN_HEADER
#ifndef YY_REENTRANT
static YY_BUFFER_STATE yy_current_buffer = 0;
#endif
/* %e */
#endif /* !yyIN_HEADER */
/* %* */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* %- Standard (non-C++) definition */

#ifndef YY_REENTRANT
/* %c */
#ifndef yyIN_HEADER
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %e */
#endif /* !yyIN_HEADER */
#endif /* end !YY_REENTRANT */

void yyrestart YY_PARAMS(( FILE *input_file YY_PROTO_LAST_ARG ));


void yy_switch_to_buffer YY_PARAMS(( YY_BUFFER_STATE new_buffer YY_PROTO_LAST_ARG ));
void yy_load_buffer_state YY_PARAMS(( YY_PROTO_ONLY_ARG ));
YY_BUFFER_STATE yy_create_buffer YY_PARAMS(( FILE *file, int size YY_PROTO_LAST_ARG ));
void yy_delete_buffer YY_PARAMS(( YY_BUFFER_STATE b YY_PROTO_LAST_ARG ));
void yy_init_buffer YY_PARAMS(( YY_BUFFER_STATE b, FILE *file YY_PROTO_LAST_ARG ));
void yy_flush_buffer YY_PARAMS(( YY_BUFFER_STATE b YY_PROTO_LAST_ARG ));

#define YY_FLUSH_BUFFER yy_flush_buffer( YY_G(yy_current_buffer) YY_CALL_LAST_ARG)

YY_BUFFER_STATE yy_scan_buffer YY_PARAMS(( char *base, yy_size_t size YY_PROTO_LAST_ARG ));
YY_BUFFER_STATE yy_scan_string YY_PARAMS(( yyconst char *yy_str YY_PROTO_LAST_ARG ));
YY_BUFFER_STATE yy_scan_bytes YY_PARAMS(( yyconst char *bytes, int len YY_PROTO_LAST_ARG ));

/* %* */


void *yyalloc YY_PARAMS(( yy_size_t YY_PROTO_LAST_ARG ));
void *yyrealloc YY_PARAMS(( void *, yy_size_t YY_PROTO_LAST_ARG ));
void yyfree YY_PARAMS(( void * YY_PROTO_LAST_ARG ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_G(yy_current_buffer) ) \
		YY_G(yy_current_buffer) =    \
            yy_create_buffer( yyin, YY_BUF_SIZE YY_CALL_LAST_ARG); \
	YY_G(yy_current_buffer)->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_G(yy_current_buffer) ) \
		YY_G(yy_current_buffer) =    \
            yy_create_buffer( yyin, YY_BUF_SIZE YY_CALL_LAST_ARG); \
	YY_G(yy_current_buffer)->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_G(yy_current_buffer)->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP
#ifndef yyIN_HEADER
typedef unsigned char YY_CHAR;
#endif /* !yyIN_HEADER */
#ifndef yyIN_HEADER
#ifndef YY_REENTRANT
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
#endif
#endif /* !yyIN_HEADER */
#ifndef yyIN_HEADER
typedef int yy_state_type;
#endif /* !yyIN_HEADER */
#ifdef YY_USE_LINENO
extern int yylineno;
#ifndef yyIN_HEADER
int yylineno = 1;
#endif /* !yyIN_HEADER */
#endif
extern char *yytext;
#define yytext_ptr yytext

/* %- Standard (non-C++) definition */
/* %c */
#ifndef yyIN_HEADER
static yy_state_type yy_get_previous_state YY_PARAMS(( YY_PROTO_ONLY_ARG ));
static yy_state_type yy_try_NUL_trans YY_PARAMS(( yy_state_type current_state  YY_PROTO_LAST_ARG));
static int yy_get_next_buffer YY_PARAMS(( YY_PROTO_ONLY_ARG ));
static void yy_fatal_error YY_PARAMS(( yyconst char msg[] YY_PROTO_LAST_ARG ));
/* %e */
#endif /* !yyIN_HEADER */
/* %* */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	YY_G(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	YY_G(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	YY_G(yy_c_buf_p) = yy_cp;

/* %* */

/* %c */
#ifndef yyIN_HEADER
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
static yyconst short int yy_accept[104] =
    {   0,
        0,    0,    0,    0,   45,   43,    2,    3,    3,    4,
        1,   42,   36,   43,   23,   40,   40,   38,   38,   27,
       38,   38,   38,   15,    6,    5,   44,    2,    3,    1,
        1,   42,   39,   40,   23,   23,   23,   23,   23,   23,
       23,    0,   38,   37,   38,   38,   38,   38,   31,   32,
       33,   38,   38,   38,   15,   14,    7,    8,   12,   13,
        9,   11,   10,   23,   23,   23,   23,   23,   23,   41,
       25,   38,   29,   30,   35,   38,   38,    7,    8,   23,
       23,   23,   23,   23,   23,   24,   28,   26,   38,    7,
       23,   19,   17,   23,   16,   18,   38,   21,   20,   38,

       22,   34,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    1,    8,
        8,    1,    1,    8,    9,   10,    1,   11,   12,   12,
       12,   12,   12,   12,   12,   13,   13,   14,    1,    1,
        1,    1,    1,    1,   15,   15,   15,   15,   15,   15,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
        1,   17,    1,    1,   18,    1,   19,   20,   21,   22,

       23,   24,   25,   16,   26,   16,   16,   27,   16,   28,
       29,   30,   31,   32,   33,   34,   35,   16,   36,   37,
       38,   39,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        5,    5,    5,    6,    5,    7,    3,    7,    5,    5,
        5,    5,    5,    5,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7
    } ;

static yyconst short int yy_base[112] =
    {   0,
        0,    0,   37,   38,  224,  225,   42,   47,   54,  225,
        0,   50,  225,   53,   48,   60,   63,  209,   55,   64,
       74,   66,   69,    0,  225,  225,   97,   99,  109,    0,
        0,    0,  107,  111,    0,  189,  183,  201,  189,  195,
      188,    0,  202,  225,   76,   65,  112,  113,  201,  200,
      199,  100,   71,  114,    0,  225,  121,  126,  225,  225,
      225,  225,  225,  191,  177,  176,  190,  171,  164,    0,
       33,  102,  181,  175,  172,  126,   85,  131,  137,  152,
      145,  148,  145,  131,  142,  149,  148,  147,  132,  142,
      134,    0,    0,  136,    0,    0,  131,  118,    0,  142,

        0,   72,  225,  169,  176,  180,  183,  186,  193,  200,
       47
    } ;

static yyconst short int yy_def[112] =
    {   0,
      103,    1,  104,  104,  103,  103,  103,  103,  103,  103,
      105,  106,  103,  103,  107,  103,  103,  108,  108,  108,
      108,  108,  108,  109,  103,  103,  110,  103,  103,  105,
      105,  106,  106,  103,  107,  107,  107,  107,  107,  107,
      107,  111,  108,  103,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  109,  103,  103,  103,  103,  103,
      103,  103,  103,  107,  107,  107,  107,  107,  107,  111,
      108,  108,  108,  108,  108,  108,  108,  103,  103,  107,
      107,  107,  107,  107,  107,  108,  108,  108,  108,  103,
      107,  107,  107,  107,  107,  107,  108,  107,  107,  108,

      107,  108,    0,  103,  103,  103,  103,  103,  103,  103,
      103
    } ;

static yyconst short int yy_nxt[265] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   17,    6,   18,   18,    6,    6,   19,   20,
       18,   18,   18,   18,   18,   18,   21,   22,   18,   18,
       18,   18,   23,   18,   18,   18,   18,   18,   18,   25,
       25,   26,   26,   28,   29,   29,   44,   30,   29,   29,
       29,   70,   30,   27,   27,   29,   29,   29,   86,   30,
       33,   33,   33,   34,   34,   34,   36,   37,   44,   38,
       34,   34,   34,   34,   34,   34,   45,   44,   44,   44,
       39,   40,   44,   41,   44,   44,   46,   44,   47,   44,
       76,   48,   49,   50,   52,   72,   42,   71,   44,   51,

       28,   29,   29,   53,   30,   89,   54,   57,   57,   58,
       29,   29,   29,   44,   30,   44,   59,   33,   33,   33,
       60,   34,   34,   34,   61,   44,   44,   44,   62,   75,
       63,   78,   78,   79,   73,   74,   79,   79,   79,   44,
       87,   90,   90,   79,   44,   44,   77,   79,   79,   79,
       97,   88,   79,   79,   79,   44,  101,  100,   99,   98,
       44,   44,   44,   96,   95,   94,   93,   92,  102,   24,
       24,   24,   24,   24,   24,   24,   31,   91,   31,   31,
       31,   31,   31,   32,   32,   44,   32,   35,   44,   35,
       43,   43,   43,   55,   44,   85,   55,   55,   55,   55,

       56,   56,   56,   56,   56,   56,   56,   84,   83,   82,
       81,   80,   44,   44,   44,   44,   69,   68,   67,   66,
       65,   64,   44,  103,    5,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103
    } ;

static yyconst short int yy_chk[265] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    3,    4,    7,    7,    7,   71,    7,    8,    8,
        8,  111,    8,    3,    4,    9,    9,    9,   71,    9,
       12,   12,   12,   14,   14,   14,   15,   15,   19,   15,
       16,   16,   16,   17,   17,   17,   19,   20,   46,   22,
       15,   15,   23,   15,   53,  102,   20,   21,   20,   45,
       53,   20,   21,   21,   22,   46,   16,   45,   77,   21,

       28,   28,   28,   23,   28,   77,   23,   27,   27,   27,
       29,   29,   29,   52,   29,   72,   27,   33,   33,   33,
       27,   34,   34,   34,   27,   47,   48,   54,   27,   52,
       27,   57,   57,   57,   47,   48,   58,   58,   58,   76,
       72,   78,   78,   78,   97,   89,   54,   79,   79,   79,
       89,   76,   90,   90,   90,  100,   98,   97,   94,   91,
       88,   87,   86,   85,   84,   83,   82,   81,  100,  104,
      104,  104,  104,  104,  104,  104,  105,   80,  105,  105,
      105,  105,  105,  106,  106,   75,  106,  107,   74,  107,
      108,  108,  108,  109,   73,   69,  109,  109,  109,  109,

      110,  110,  110,  110,  110,  110,  110,   68,   67,   66,
       65,   64,   51,   50,   49,   43,   41,   40,   39,   38,
       37,   36,   18,    5,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103
    } ;

#ifdef YY_USE_LINENO
/* Table of booleans, true if rule could match eol. */
static const int yy_rule_can_match_eol[45] =
    {
    0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0
    };
#endif
static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YY_REENTRANT
char *yytext;
#endif
#line 1 "asm/scanner.lex"
#define INITIAL 0
#define YY_NO_UNPUT 1
#define YY_USE_LINENO 1
#line 5 "asm/scanner.lex"
#include "sim/types.h"
#include <iostream>     
#include <cstring>
#include <stdlib.h>
#include <limits.h>
#include "rasm.tab.hpp"

using namespace std;

const int32_t MAX_STR_CONST = 0x9000;
char string_buf[MAX_STR_CONST];
char *string_buf_ptr;
extern int32_t yylineno;

#define string 1

#line 682 "lex.yy.c"
/* %e */
#endif /* !yyIN_HEADER */

/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#ifndef YY_NO_UNISTD_H
/* %- */
#include <unistd.h>
/* %+ */
/* %* */
#endif /* !YY_NO_UNISTD_H */


#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %- Reentrant structure and macros (non-C++). */
#ifdef YY_REENTRANT

/* %c */
#ifndef yyIN_HEADER
/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    YY_BUFFER_STATE yy_current_buffer;
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

#ifdef YY_TEXT_IS_ARRAY
    char yytext_r[YYLMAX];
    char *yytext_ptr;
    int yy_more_offset;
    int yy_prev_more_offset;
#else
    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;
#endif

#ifdef YY_REENTRANT_BISON_PURE
    YYSTYPE * yylval_r;
#ifdef YYLTYPE
    YYLTYPE * yylloc_r;
#endif
#endif

    };
/* %e */
#endif /* !yyIN_HEADER */

/* %c */
#ifndef yyIN_HEADER
static int yy_init_globals YY_PARAMS(( YY_PROTO_ONLY_ARG ));
/* %e */
#endif /* !yyIN_HEADER */

/* This must go here because YYSTYPE and YYLSTYPE are included
 * from bison output in section 1.*/
#ifdef YY_REENTRANT_BISON_PURE
#    define yylval YY_G(yylval_r)
#  ifdef YYLTYPE
#    define yylloc YY_G(yylloc_r)
#  endif
#endif /* YY_REENTRANT_BISON_PURE */

#endif /* end if YY_REENTRANT */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

#ifndef YY_NO_DESTROY
int yylex_destroy YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif

#ifndef YY_NO_GET_DEBUG
int yyget_debug YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif

#ifndef YY_NO_SET_DEBUG
void yyset_debug YY_PARAMS(( int debug_flag YY_PROTO_LAST_ARG ));
#endif

#ifndef YY_NO_GET_EXTRA
YY_EXTRA_TYPE yyget_extra YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif

#ifndef YY_NO_SET_EXTRA
void yyset_extra YY_PARAMS(( YY_EXTRA_TYPE user_defined YY_PROTO_LAST_ARG ));
#endif

#ifndef YY_NO_GET_IN
FILE *yyget_in YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif

#ifndef YY_NO_SET_IN
void yyset_in  YY_PARAMS(( FILE * in_str YY_PROTO_LAST_ARG ));
#endif

#ifndef YY_NO_GET_OUT
FILE *yyget_out YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif

#ifndef YY_NO_SET_OUT
void yyset_out  YY_PARAMS(( FILE * out_str YY_PROTO_LAST_ARG ));
#endif

#ifndef YY_NO_GET_LENG
int yyget_leng YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif

#ifndef YY_NO_GET_TEXT
char *yyget_text YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif

#ifndef YY_NO_GET_LINENO
int yyget_lineno YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif

#ifndef YY_NO_SET_LINENO
void yyset_lineno YY_PARAMS(( int line_number YY_PROTO_LAST_ARG ));
#endif

#ifdef YY_REENTRANT_BISON_PURE
#ifndef YY_NO_GET_LVAL
YYSTYPE * yyget_lval YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif
void yyset_lval YY_PARAMS(( YYSTYPE * yylvalp YY_PROTO_LAST_ARG ));
#ifdef YYLTYPE
#ifndef YY_NO_GET_LLOC
   YYLTYPE *yyget_lloc YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif
#ifndef YY_NO_SET_LLOC
    void yyset_lloc YY_PARAMS(( YYLTYPE * yyllocp YY_PROTO_LAST_ARG ));
#endif
#endif /* YYLTYPE */
#endif /* YY_REENTRANT_BISON_PURE */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#else
extern int yywrap YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif
#endif

/* %- */
/* %c */
#ifndef yyIN_HEADER
#ifndef YY_NO_UNPUT
static void yyunput YY_PARAMS(( int c, char *buf_ptr  YY_PROTO_LAST_ARG));
#endif
/* %e */
#endif /* !yyIN_HEADER */
/* %* */

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PARAMS(( char *, yyconst char *, int YY_PROTO_LAST_ARG));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PARAMS(( yyconst char * YY_PROTO_LAST_ARG));
#endif

#ifndef YY_NO_INPUT
/* %- Standard (non-C++) definition */
/* %c */
#ifndef yyIN_HEADER
#ifdef __cplusplus
static int yyinput YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#else
static int input YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif
/* %e */
#endif /* !yyIN_HEADER */
/* %* */
#endif

#if YY_STACK_USED
#ifndef YY_REENTRANT
/* %c */
#ifndef yyIN_HEADER
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
/* %e */
#endif /* !yyIN_HEADER */
#endif
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PARAMS(( int new_state YY_PROTO_LAST_ARG));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PARAMS(( YY_PROTO_ONLY_ARG ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* %- Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
/* %+ C++ definition */
/* %* */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_G(yy_current_buffer)->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
/* %+ C++ definition \ */\
/* %* */
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %- */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg YY_CALL_LAST_ARG)
/* %+ */
/* %* */
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
/* %- Standard (non-C++) definition */

/* If the bison pure parser is used, then bison will provide
   one or two additional arguments. */

#ifdef YY_REENTRANT_BISON_PURE
#  ifdef YYLTYPE 
#        define YY_LEX_PROTO YY_PARAMS((YYSTYPE * yylvalp, YYLTYPE * yyllocp YY_PROTO_LAST_ARG))
#        define YY_LEX_DECLARATION YYFARGS2(YYSTYPE *,yylvalp, YYLTYPE *,yyllocp)
#  else
#        define YY_LEX_PROTO YY_PARAMS((YYSTYPE * yylvalp YY_PROTO_LAST_ARG))
#        define YY_LEX_DECLARATION YYFARGS1(YYSTYPE *,yylvalp)
#  endif
#else
#      define YY_LEX_PROTO YY_PARAMS((YY_PROTO_ONLY_ARG))
#      define YY_LEX_DECLARATION YYFARGS0(void)
#endif


extern int yylex YY_LEX_PROTO;

#define YY_DECL int yylex YY_LEX_DECLARATION
/* %+ C++ definition */
/* %* */
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %c */
#ifndef yyIN_HEADER
YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

/* %% [7.0] user's declarations go here */
#line 29 "asm/scanner.lex"


#line 1045 "lex.yy.c"

#ifdef YY_REENTRANT_BISON_PURE
    yylval = yylvalp;
#ifdef YYLTYPE
    yylloc = yyllocp;
#endif
#endif

	if ( YY_G(yy_init) )
		{
		YY_G(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! YY_G(yy_start) )
			YY_G(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %- */
			yyin = stdin;
/* %+ */
/* %* */

		if ( ! yyout )
/* %- */
			yyout = stdout;
/* %+ */
/* %* */

		if ( ! YY_G(yy_current_buffer) )
			YY_G(yy_current_buffer) =
				yy_create_buffer( yyin, YY_BUF_SIZE YY_CALL_LAST_ARG);

		yy_load_buffer_state( YY_CALL_ONLY_ARG );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = YY_G(yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = YY_G(yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = YY_G(yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				YY_G(yy_last_accepting_state) = yy_current_state;
				YY_G(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 104 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 225 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = YY_G(yy_last_accepting_cpos);
			yy_current_state = YY_G(yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */
#ifdef YY_USE_LINENO
		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}
#endif

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = YY_G(yy_hold_char);
			yy_cp = YY_G(yy_last_accepting_cpos);
			yy_current_state = YY_G(yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol = true*/
YY_RULE_SETUP
#line 31 "asm/scanner.lex"
/*ignore comment lines*/
	YY_BREAK
case 2:
/* rule 2 can match eol = false*/
YY_RULE_SETUP
#line 33 "asm/scanner.lex"
/* ignore whitespace */
	YY_BREAK
case 3:
/* rule 3 can match eol = true*/
YY_RULE_SETUP
#line 35 "asm/scanner.lex"
{
 // found a newline. should terminate current context, etc. 
 // collapses multiple blank lines to a single newline.
 return NEWLINE;
}
	YY_BREAK
case 4:
/* rule 4 can match eol = false*/
YY_RULE_SETUP
#line 42 "asm/scanner.lex"
{
  string_buf_ptr = string_buf; 
  BEGIN(string);
}
	YY_BREAK
case 5:
/* rule 5 can match eol = false*/
YY_RULE_SETUP
#line 46 "asm/scanner.lex"
{ 
  BEGIN(INITIAL);
  *string_buf_ptr = '\0';
  int32_t length = string_buf_ptr - string_buf; // null deliberately left out; this is asm!
  yylval.sysstring.ptr = string_buf;
  yylval.sysstring.len = length;
  return STRING;
}
	YY_BREAK
case 6:
/* rule 6 can match eol = true*/
YY_RULE_SETUP
#line 54 "asm/scanner.lex"
{
     cerr << "unterminated string constant; line " << yylineno << endl;
     exit(10);
}
	YY_BREAK
case 7:
/* rule 7 can match eol = false*/
YY_RULE_SETUP
#line 58 "asm/scanner.lex"
{
    /* octal escape sequence */
    int32_t result;
    sscanf(yytext + 1, "%o", &result);
    if (result > 0xff) {
      /* error, constant is out-of-bounds */
       cerr << "octal escape sequence is too large; line " << yylineno << endl;
       exit(10);
    }
    *string_buf_ptr++ = result;
}
	YY_BREAK
case 8:
/* rule 8 can match eol = false*/
YY_RULE_SETUP
#line 69 "asm/scanner.lex"
{
   cerr << "bad escape sequence; line " << yylineno << endl;
   exit(10);
}
	YY_BREAK
case 9:
/* rule 9 can match eol = false*/
YY_RULE_SETUP
#line 73 "asm/scanner.lex"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 10:
/* rule 10 can match eol = false*/
YY_RULE_SETUP
#line 74 "asm/scanner.lex"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 11:
/* rule 11 can match eol = false*/
YY_RULE_SETUP
#line 75 "asm/scanner.lex"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 12:
/* rule 12 can match eol = false*/
YY_RULE_SETUP
#line 76 "asm/scanner.lex"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 13:
/* rule 13 can match eol = false*/
YY_RULE_SETUP
#line 77 "asm/scanner.lex"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 14:
/* rule 14 can match eol = true*/
YY_RULE_SETUP
#line 78 "asm/scanner.lex"
{*string_buf_ptr++ = yytext[1];}
	YY_BREAK
case 15:
/* rule 15 can match eol = false*/
YY_RULE_SETUP
#line 79 "asm/scanner.lex"
{
  char *yptr = (char*)yytext;
  while (*yptr) {
   *string_buf_ptr++ = *yptr++;
  }
}
	YY_BREAK
case 16:
/* rule 16 can match eol = false*/
YY_RULE_SETUP
#line 86 "asm/scanner.lex"
{return TEXT_SECTION;}
	YY_BREAK
case 17:
/* rule 17 can match eol = false*/
YY_RULE_SETUP
#line 87 "asm/scanner.lex"
{return DATA_SECTION;}
	YY_BREAK
case 18:
/* rule 18 can match eol = false*/
YY_RULE_SETUP
#line 88 "asm/scanner.lex"
{return WORD; }
	YY_BREAK
case 19:
/* rule 19 can match eol = false*/
YY_RULE_SETUP
#line 89 "asm/scanner.lex"
{return BYTE; }
	YY_BREAK
case 20:
/* rule 20 can match eol = false*/
YY_RULE_SETUP
#line 90 "asm/scanner.lex"
{return SPACE;}
	YY_BREAK
case 21:
/* rule 21 can match eol = false*/
YY_RULE_SETUP
#line 91 "asm/scanner.lex"
{return ASCII;}
	YY_BREAK
case 22:
/* rule 22 can match eol = false*/
YY_RULE_SETUP
#line 92 "asm/scanner.lex"
{return ASCIIZ;}
	YY_BREAK
case 23:
/* rule 23 can match eol = false*/
YY_RULE_SETUP
#line 93 "asm/scanner.lex"
{return SECTION_IDENT; /*for error reporting*/}
	YY_BREAK
case 24:
/* rule 24 can match eol = false*/
YY_RULE_SETUP
#line 96 "asm/scanner.lex"
{return ADDI;      }
	YY_BREAK
case 25:
/* rule 25 can match eol = false*/
YY_RULE_SETUP
#line 97 "asm/scanner.lex"
{return ADD;       }
	YY_BREAK
case 26:
/* rule 26 can match eol = false*/
YY_RULE_SETUP
#line 98 "asm/scanner.lex"
{return SUBI;      }
	YY_BREAK
case 27:
/* rule 27 can match eol = false*/
YY_RULE_SETUP
#line 99 "asm/scanner.lex"
{return BRANCH;    }
	YY_BREAK
case 28:
/* rule 28 can match eol = false*/
YY_RULE_SETUP
#line 100 "asm/scanner.lex"
{return BRANCHEQZ; }
	YY_BREAK
case 29:
/* rule 29 can match eol = false*/
YY_RULE_SETUP
#line 101 "asm/scanner.lex"
{return BRANCHGE;  }
	YY_BREAK
case 30:
/* rule 30 can match eol = false*/
YY_RULE_SETUP
#line 102 "asm/scanner.lex"
{return BRANCHNE;  }
	YY_BREAK
case 31:
/* rule 31 can match eol = false*/
YY_RULE_SETUP
#line 103 "asm/scanner.lex"
{return LOADADDR;  }
	YY_BREAK
case 32:
/* rule 32 can match eol = false*/
YY_RULE_SETUP
#line 104 "asm/scanner.lex"
{return LOADBYTE;  }
	YY_BREAK
case 33:
/* rule 33 can match eol = false*/
YY_RULE_SETUP
#line 105 "asm/scanner.lex"
{return LOADIMMED; }
	YY_BREAK
case 34:
/* rule 34 can match eol = false*/
YY_RULE_SETUP
#line 106 "asm/scanner.lex"
{return SYSCALL;   }
	YY_BREAK
case 35:
/* rule 35 can match eol = false*/
YY_RULE_SETUP
#line 107 "asm/scanner.lex"
{return NOOP;      }
	YY_BREAK
case 36:
/* rule 36 can match eol = false*/
YY_RULE_SETUP
#line 110 "asm/scanner.lex"
{ return *yytext; /* punctuation marks */}
	YY_BREAK
case 37:
/* rule 37 can match eol = false*/
YY_RULE_SETUP
#line 112 "asm/scanner.lex"
{
  // Found a label decl.
  int32_t sl = strlen(yytext);
  yytext[sl-1] = 0; // take out colon
  yylval.sysstring.len = sl;
  yylval.sysstring.ptr = yytext; 
  return LABELDECL;
}
	YY_BREAK
case 38:
/* rule 38 can match eol = false*/
YY_RULE_SETUP
#line 121 "asm/scanner.lex"
{
  // Found a label ref. 
  int32_t sl = strlen(yytext);
  yylval.sysstring.len = sl;
  yylval.sysstring.ptr = yytext;
  return LABELREF;
}
	YY_BREAK
case 39:
/* rule 39 can match eol = false*/
YY_RULE_SETUP
#line 129 "asm/scanner.lex"
{
  // found a register reference
  yylval.sysword = strtol(yytext+1, NULL, 10);
  if (yylval.sysword < 0 || yylval.sysword > 31) {
    cerr << "invalid register \'"<< yytext << "\'; line " << yylineno << endl;
    exit(10);
  }
  return REGISTER;
}
	YY_BREAK
case 40:
/* rule 40 can match eol = false*/
YY_RULE_SETUP
#line 139 "asm/scanner.lex"
{
  // found an integer
  yylval.sysword = strtol(yytext, NULL, 10);
  return INTEGER;
}
	YY_BREAK
case 41:
/* rule 41 can match eol = false*/
YY_RULE_SETUP
#line 145 "asm/scanner.lex"
{
  // found an integer
  yylval.sysword = strtol(yytext, NULL, 16);
  return INTEGER;
}
	YY_BREAK
case 42:
/* rule 42 can match eol = false*/
YY_RULE_SETUP
#line 151 "asm/scanner.lex"
{
  return INVALID_REGISTER;
}
	YY_BREAK
case 43:
/* rule 43 can match eol = false*/
YY_RULE_SETUP
#line 155 "asm/scanner.lex"
{
  cerr << "invalid character; line " << yylineno << endl;
  exit(10);
}
	YY_BREAK
case 44:
/* rule 44 can match eol = false*/
YY_RULE_SETUP
#line 160 "asm/scanner.lex"
ECHO;
	YY_BREAK
#line 1489 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - YY_G(yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = YY_G(yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_G(yy_current_buffer)->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_n_chars;
			YY_G(yy_current_buffer)->yy_input_file = yyin;
			YY_G(yy_current_buffer)->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( YY_G(yy_c_buf_p) <= &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			YY_G(yy_c_buf_p) = YY_G(yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( YY_CALL_ONLY_ARG );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state YY_CALL_LAST_ARG);

			yy_bp = YY_G(yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++YY_G(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = YY_G(yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( YY_CALL_ONLY_ARG ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				YY_G(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( YY_CALL_ONLY_ARG ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					YY_G(yy_c_buf_p) = YY_G(yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! YY_G(yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				YY_G(yy_c_buf_p) =
					YY_G(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( YY_CALL_ONLY_ARG );

				yy_cp = YY_G(yy_c_buf_p);
				yy_bp = YY_G(yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				YY_G(yy_c_buf_p) =
				&YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)];

				yy_current_state = yy_get_previous_state( YY_CALL_ONLY_ARG );

				yy_cp = YY_G(yy_c_buf_p);
				yy_bp = YY_G(yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */
/* %e */
#endif /* !yyIN_HEADER */
/* %+ */
/* %c */
#ifndef yyIN_HEADER
/* %e */
#endif /* !yyIN_HEADER */
/* %* */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

/* %- */
/* %c */
#ifndef yyIN_HEADER
static int yy_get_next_buffer YYFARGS0(void)
/* %+ */
/* %* */
	{
	register char *dest = YY_G(yy_current_buffer)->yy_ch_buf;
	register char *source = YY_G(yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( YY_G(yy_c_buf_p) > &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_G(yy_current_buffer)->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( YY_G(yy_c_buf_p) - YY_G(yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (YY_G(yy_c_buf_p) - YY_G(yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_G(yy_current_buffer)->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars) = 0;

	else
		{
			size_t num_to_read =
			YY_G(yy_current_buffer)->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_G(yy_current_buffer);

			int yy_c_buf_p_offset =
				(int) (YY_G(yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 YY_CALL_LAST_ARG );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			YY_G(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_G(yy_current_buffer)->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_G(yy_current_buffer)->yy_ch_buf[number_to_move]),
			YY_G(yy_n_chars), num_to_read );

		YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars);
		}

	if ( YY_G(yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  YY_CALL_LAST_ARG);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_G(yy_current_buffer)->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	YY_G(yy_n_chars) += number_to_move;
	YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	YY_G(yytext_ptr) = &YY_G(yy_current_buffer)->yy_ch_buf[0];

	return ret_val;
	}
/* %e */
#endif /* !yyIN_HEADER */

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %- */
/* %c */
#ifndef yyIN_HEADER
static yy_state_type yy_get_previous_state YYFARGS0(void)
/* %+ */
/* %* */
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = YY_G(yy_start);

	for ( yy_cp = YY_G(yytext_ptr) + YY_MORE_ADJ; yy_cp < YY_G(yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			YY_G(yy_last_accepting_state) = yy_current_state;
			YY_G(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 104 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

/* %- */
static yy_state_type yy_try_NUL_trans  YYFARGS1( yy_state_type, yy_current_state)
/* %+ */
/* %* */
	{
	register int yy_is_jam;
/* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = YY_G(yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		YY_G(yy_last_accepting_state) = yy_current_state;
		YY_G(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 104 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 103);

	return yy_is_jam ? 0 : yy_current_state;
	}


/* %- */
#ifndef YY_NO_UNPUT
static void yyunput YYFARGS2( int,c, register char *,yy_bp)
/* %+ */
/* %* */
	{
	register char *yy_cp = YY_G(yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = YY_G(yy_hold_char);

	if ( yy_cp < YY_G(yy_current_buffer)->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = YY_G(yy_n_chars) + 2;
		register char *dest = &YY_G(yy_current_buffer)->yy_ch_buf[
					YY_G(yy_current_buffer)->yy_buf_size + 2];
		register char *source =
				&YY_G(yy_current_buffer)->yy_ch_buf[number_to_move];

		while ( source > YY_G(yy_current_buffer)->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_G(yy_current_buffer)->yy_n_chars =
			YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_buf_size;

		if ( yy_cp < YY_G(yy_current_buffer)->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */
#ifdef YY_USE_LINENO
    if ( c == '\n' )
        --yylineno;
#endif
	YY_G(yytext_ptr) = yy_bp;
	YY_G(yy_hold_char) = *yy_cp;
	YY_G(yy_c_buf_p) = yy_cp;
	}
/* %- */
#endif	/* ifndef YY_NO_UNPUT */
/* %* */


/* %- */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YYFARGS0(void)
#else
static int input  YYFARGS0(void)
#endif
/* %+ */
/* %* */
	{
	int c;

	*YY_G(yy_c_buf_p) = YY_G(yy_hold_char);

	if ( *YY_G(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( YY_G(yy_c_buf_p) < &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] )
			/* This was really a NUL. */
			*YY_G(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = YY_G(yy_c_buf_p) - YY_G(yytext_ptr);
			++YY_G(yy_c_buf_p);

			switch ( yy_get_next_buffer( YY_CALL_ONLY_ARG ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin YY_CALL_LAST_ARG);

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( YY_CALL_ONLY_ARG ) )
						return EOF;

					if ( ! YY_G(yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(YY_CALL_ONLY_ARG);
#else
					return input(YY_CALL_ONLY_ARG);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					YY_G(yy_c_buf_p) = YY_G(yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) YY_G(yy_c_buf_p);	/* cast for 8-bit char's */
	*YY_G(yy_c_buf_p) = '\0';	/* preserve yytext */
	YY_G(yy_hold_char) = *++YY_G(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	if ( c == '\n' )
		++yylineno;

	return c;
	}
/* %- */
#endif	/* ifndef YY_NO_INPUT */
/* %* */

/* %- */
void yyrestart  YYFARGS1( FILE *,input_file)
/* %+ */
/* %* */
	{
	if ( ! YY_G(yy_current_buffer) )
		YY_G(yy_current_buffer) =
            yy_create_buffer( yyin, YY_BUF_SIZE YY_CALL_LAST_ARG);

	yy_init_buffer( YY_G(yy_current_buffer), input_file YY_CALL_LAST_ARG);
	yy_load_buffer_state( YY_CALL_ONLY_ARG );
	}


/* %- */
void yy_switch_to_buffer  YYFARGS1( YY_BUFFER_STATE ,new_buffer)
/* %+ */
/* %* */
	{
	if ( YY_G(yy_current_buffer) == new_buffer )
		return;

	if ( YY_G(yy_current_buffer) )
		{
		/* Flush out information for old buffer. */
		*YY_G(yy_c_buf_p) = YY_G(yy_hold_char);
		YY_G(yy_current_buffer)->yy_buf_pos = YY_G(yy_c_buf_p);
		YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars);
		}

	YY_G(yy_current_buffer) = new_buffer;
	yy_load_buffer_state( YY_CALL_ONLY_ARG );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	YY_G(yy_did_buffer_switch_on_eof) = 1;
	}


/* %- */
void yy_load_buffer_state  YYFARGS0(void)
/* %+ */
/* %* */
	{
	YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_n_chars;
	YY_G(yytext_ptr) = YY_G(yy_c_buf_p) = YY_G(yy_current_buffer)->yy_buf_pos;
	yyin = YY_G(yy_current_buffer)->yy_input_file;
	YY_G(yy_hold_char) = *YY_G(yy_c_buf_p);
	}


/* %- */
YY_BUFFER_STATE yy_create_buffer  YYFARGS2( FILE *,file, int ,size)
/* %+ */
/* %* */
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) YY_CALL_LAST_ARG );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( b->yy_buf_size + 2 YY_CALL_LAST_ARG );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file YY_CALL_LAST_ARG);

	return b;
	}


/* %- */
void yy_delete_buffer YYFARGS1( YY_BUFFER_STATE ,b)
/* %+ */
/* %* */
	{
	if ( ! b )
		return;

	if ( b == YY_G(yy_current_buffer) )
		YY_G(yy_current_buffer) = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf YY_CALL_LAST_ARG );

	yyfree( (void *) b YY_CALL_LAST_ARG );
	}


/* %- */
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
#ifndef __cplusplus
extern int isatty YY_PARAMS(( int ));
#endif /* __cplusplus */
#endif /* !YY_NEVER_INTERACTIVE */
#endif /* !YY_ALWAYS_INTERACTIVE */

void yy_init_buffer  YYFARGS2( YY_BUFFER_STATE ,b, FILE *,file)
/* %+ */
/* %* */

	{
	int oerrno = errno;

	yy_flush_buffer( b YY_CALL_LAST_ARG);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

/* %- */
#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
/* %+ */
/* %* */
	errno = oerrno;
	}


/* %- */
void yy_flush_buffer YYFARGS1( YY_BUFFER_STATE ,b)
/* %+ */
/* %* */
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_G(yy_current_buffer) )
		yy_load_buffer_state( YY_CALL_ONLY_ARG );
	}
/* %* */


#ifndef YY_NO_SCAN_BUFFER
/* %- */
YY_BUFFER_STATE yy_scan_buffer  YYFARGS2( char *,base, yy_size_t ,size)
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) YY_CALL_LAST_ARG );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b YY_CALL_LAST_ARG );

	return b;
	}
/* %* */
#endif


#ifndef YY_NO_SCAN_STRING
/* %- */
YY_BUFFER_STATE yy_scan_string YYFARGS1( yyconst char *,yy_str)
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len YY_CALL_LAST_ARG);
	}
/* %* */
#endif


#ifndef YY_NO_SCAN_BYTES
/* %- */
YY_BUFFER_STATE yy_scan_bytes  YYFARGS2( yyconst char *,bytes, int ,len)
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yyalloc( n YY_CALL_LAST_ARG );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n YY_CALL_LAST_ARG);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
/* %* */
#endif


#ifndef YY_NO_PUSH_STATE
/* %- */
static void yy_push_state YYFARGS1( int ,new_state)
/* %+ */
/* %* */
	{
	if ( YY_G(yy_start_stack_ptr) >= YY_G(yy_start_stack_depth) )
		{
		yy_size_t new_size;

		YY_G(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = YY_G(yy_start_stack_depth) * sizeof( int );

		if ( ! YY_G(yy_start_stack) )
			YY_G(yy_start_stack) = (int *) yyalloc( new_size YY_CALL_LAST_ARG );

		else
			YY_G(yy_start_stack) = (int *) yyrealloc(
					(void *) YY_G(yy_start_stack), new_size YY_CALL_LAST_ARG );

		if ( ! YY_G(yy_start_stack) )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
/* %- */
static void yy_pop_state  YYFARGS0(void)
/* %+ */
/* %* */
	{
	if ( --YY_G(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr)]);
	}
#endif


#ifndef YY_NO_TOP_STATE
/* %- */
static int yy_top_state  YYFARGS0(void)
/* %+ */
/* %* */
	{
	return YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr) - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %- */
static void yy_fatal_error YYFARGS1(yyconst char*, msg)
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}

/* %+ */
/* %* */


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        YY_LESS_LINENO(n);\
		yytext[yyleng] = YY_G(yy_hold_char); \
		YY_G(yy_c_buf_p) = yytext + n; \
		YY_G(yy_hold_char) = *YY_G(yy_c_buf_p); \
		*YY_G(yy_c_buf_p) = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )



#ifdef YY_REENTRANT

/* Accessor  methods (get/set functions) to struct members. */

#ifndef YY_NO_GET_EXTRA
YY_EXTRA_TYPE yyget_extra  YYFARGS0(void)
{
    return yyextra;
}
#endif /* !YY_NO_GET_EXTRA */

#ifndef YY_NO_GET_LINENO
int yyget_lineno  YYFARGS0(void)
{
    return yylineno;
}
#endif /* !YY_NO_GET_LINENO */

#ifndef YY_NO_GET_IN
FILE *yyget_in  YYFARGS0(void)
{
    return yyin;
}
#endif /* !YY_NO_GET_IN */

#ifndef YY_NO_GET_OUT
FILE *yyget_out  YYFARGS0(void)
{
    return yyout;
}
#endif /* !YY_NO_GET_OUT */

#ifndef YY_NO_GET_LENG
int yyget_leng  YYFARGS0(void)
{
    return yyleng;
}
#endif /* !YY_NO_GET_LENG */

#ifndef YY_NO_GET_TEXT
char *yyget_text  YYFARGS0(void)
{
    return yytext;
}
#endif /* !YY_NO_GET_TEXT */

#ifndef YY_NO_SET_EXTRA
void yyset_extra YYFARGS1( YY_EXTRA_TYPE ,user_defined)
{
    yyextra = user_defined ;
}
#endif /* !YY_NO_SET_EXTRA */

#ifndef YY_NO_SET_LINENO
void yyset_lineno YYFARGS1( int ,line_number)
{
    yylineno = line_number;
}
#endif /* !YY_NO_SET_LINENO */


#ifndef YY_NO_SET_IN
void yyset_in YYFARGS1( FILE * ,in_str)
{
    yyin = in_str ;
}
#endif /* !YY_NO_SET_IN */

#ifndef YY_NO_SET_OUT
void yyset_out YYFARGS1( FILE * ,out_str)
{
    yyout = out_str ;
}
#endif /* !YY_NO_SET_OUT */


#ifndef YY_NO_GET_DEBUG
int yyget_debug  YYFARGS0(void)
{
    return yy_flex_debug;
}
#endif /* !YY_NO_GET_DEBUG */

#ifndef YY_NO_SET_DEBUG
void yyset_debug YYFARGS1( int ,bdebug)
{
    yy_flex_debug = bdebug ;
}
#endif /* !YY_NO_SET_DEBUG */


/* Accessor methods for yylval and yylloc */

#ifdef YY_REENTRANT_BISON_PURE
#ifndef YY_NO_GET_LVAL
YYSTYPE * yyget_lval  YYFARGS0(void)
{
    return yylval;
}
#endif /* !YY_NO_GET_LVAL */

#ifndef YY_NO_SET_LVAL
void yyset_lval YYFARGS1( YYSTYPE * ,yylvalp)
{
    yylval = yylvalp;
}
#endif /* !YY_NO_SET_LVAL */

#ifdef YYLTYPE
#ifndef YY_NO_GET_LLOC
YYLTYPE *yyget_lloc  YYFARGS0(void)
{
    return yylloc;
}
#endif /* !YY_NO_GET_LLOC */

#ifndef YY_NO_SET_LLOC
void yyset_lloc YYFARGS1( YYLTYPE * ,yyllocp)
{
    yylloc = yyllocp;
}
#endif /* !YY_NO_SET_LLOC */

#endif /* YYLTYPE */
#endif /* YY_REENTRANT_BISON_PURE */


static int yy_init_globals YYFARGS0(void)
    {
    /* Initialization is the same as for the non-reentrant scanner.
       This function is called once per scanner lifetime. */

  /* We do not touch yylineno unless the option is enabled. */
#ifdef YY_USE_LINENO
    yylineno =  1;
#endif
    YY_G(yy_current_buffer) = 0;
    YY_G(yy_c_buf_p) = (char *) 0;
    YY_G(yy_init) = 1;
    YY_G(yy_start) = 0;
    YY_G(yy_start_stack_ptr) = 0;
    YY_G(yy_start_stack_depth) = 0;
    YY_G(yy_start_stack) = (int *) 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif
    return 0;
    }

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
#ifndef YY_TRADITIONAL_FUNC_DEFS
int yylex_init(yyscan_t* ptr_yy_globals)
#else
int yylex_init( ptr_yy_globals )
    yyscan_t* ptr_yy_globals;
#endif
    {
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );
    yy_init_globals ( *ptr_yy_globals );
    return 0;
    }

#endif /* End YY_REENTRANT */

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  YYFARGS0(void)
{
    /* Destroy the current (main) buffer. */
    yy_delete_buffer( YY_G(yy_current_buffer) YY_CALL_LAST_ARG );
    YY_G(yy_current_buffer) = NULL;


#if defined(YY_STACK_USED) || defined(YY_REENTRANT)
    /* Destroy the start condition stack. */
    if (YY_G(yy_start_stack) ){
        yyfree( YY_G(yy_start_stack) YY_CALL_LAST_ARG );
        YY_G(yy_start_stack) = NULL;
    }
#endif

#ifdef YY_REENTRANT
    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner YY_CALL_LAST_ARG );
#endif
    return 0;
}


/* Internal utility routines. */

#ifndef yytext_ptr
static void yy_flex_strncpy YYFARGS3( char*,s1, yyconst char *,s2, int,n)
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YYFARGS1( yyconst char *,s)
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif

/* You may override yyalloc by defining YY_NO_FLEX_ALLOC and linking to
 * your own version */
#ifndef YY_NO_FLEX_ALLOC
void *yyalloc YYFARGS1( yy_size_t ,size)
	{
	return (void *) malloc( size );
	}
#endif

/* You may override yyrealloc by defining YY_NO_FLEX_REALLOC and linking
 * to your own version. */
#ifndef YY_NO_FLEX_REALLOC
void *yyrealloc  YYFARGS2( void *,ptr, yy_size_t ,size)
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}
#endif

/* You may override yyfree by defining YY_NO_FLEX_FREE and linking to
 * your own version.*/
#ifndef YY_NO_FLEX_FREE
void yyfree YYFARGS1( void *,ptr)
	{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
	}
#endif

#if YY_MAIN
int main YY_PARAMS((void));

int main ()
	{

#ifdef YY_REENTRANT
    yyscan_t lexer;
    yylex_init(&lexer);
    yylex( lexer );
    yylex_destroy( lexer);

#else
	yylex();
#endif

	return 0;
	}
#endif
/* %e */
#endif /* !yyIN_HEADER */
#line 160 "asm/scanner.lex"
#ifndef yyIN_HEADER

/* A Bison parser, made by GNU Bison 1.875.  */

/* Skeleton parser for Yacc-like parsing with Bison,
   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.  */

/* As a special exception, when this file is copied by Bison into a
   Bison output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison.  */

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     NEWLINE = 258,
     TEXT_SECTION = 259,
     DATA_SECTION = 260,
     LABELDECL = 261,
     INTEGER = 262,
     LABELREF = 263,
     REGISTER = 264,
     INVALID_REGISTER = 265,
     ADDI = 266,
     ADD = 267,
     SUBI = 268,
     BRANCH = 269,
     BRANCHEQZ = 270,
     BRANCHGE = 271,
     BRANCHNE = 272,
     LOADADDR = 273,
     LOADBYTE = 274,
     LOADIMMED = 275,
     SYSCALL = 276,
     NOOP = 277,
     WORD = 278,
     BYTE = 279,
     SPACE = 280,
     ASCII = 281,
     ASCIIZ = 282,
     STRING = 283,
     SECTION_IDENT = 284
   };
#endif
#define NEWLINE 258
#define TEXT_SECTION 259
#define DATA_SECTION 260
#define LABELDECL 261
#define INTEGER 262
#define LABELREF 263
#define REGISTER 264
#define INVALID_REGISTER 265
#define ADDI 266
#define ADD 267
#define SUBI 268
#define BRANCH 269
#define BRANCHEQZ 270
#define BRANCHGE 271
#define BRANCHNE 272
#define LOADADDR 273
#define LOADBYTE 274
#define LOADIMMED 275
#define SYSCALL 276
#define NOOP 277
#define WORD 278
#define BYTE 279
#define SPACE 280
#define ASCII 281
#define ASCIIZ 282
#define STRING 283
#define SECTION_IDENT 284




#if ! defined (YYSTYPE) && ! defined (YYSTYPE_IS_DECLARED)
typedef int YYSTYPE;
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
# define YYSTYPE_IS_TRIVIAL 1
#endif

extern YYSTYPE yylval;



#endif /* !yyIN_HEADER */
